### ISSUE TITLE
大佬在吗，我想问你一些关于pico的问题~

### ISSUE THREAD

**Issue by EmpertyZ** [zk-wz/blender-bangumi#4]
大佬你好呀，看到你在alvr项目上有提问，想问一下，你有用过PICO OS5.7做串流吗？我用PICO4做串流无法识别到手势，就是握拳后，VR里面的手掌没法变成握的。想问下大佬有没有遇到过这个情况，有没有办法解决~希望大佬看到能留个言，谢谢大佬！

**Comment by zk-wz** [comment]
> 大佬你好呀，看到你在alvr项目上有提问，想问一下，你有用过PICO OS5.7做串流吗？我用PICO4做串流无法识别到手势，就是握拳后，VR里面的手掌没法变成握的。想问下大佬有没有遇到过这个情况，有没有办法解决~希望大佬看到能留个言，谢谢大佬！

要看游戏是否支持，half life alyx是可以做到你说的效果的，但有些游戏没有直接支持手势，你可以在设置里面把手柄模拟换成index指虎手柄。

另外目前先不要用最新版的alvr，v20.2.0就行，最新的他们重构了太多东西，支持又开始变得不完善了，建议完善之后再更新。

pico os也先不要升级5.8，他们5.8把openxr的sdk搞乱了导致手势和手柄无法共存，问题我都已经反馈过了，正式版出来应该会解决。

**Comment by EmpertyZ** [comment]
谢谢大佬回答，我试试看有没有用
